name: CI Tests
on: push

jobs:
  ci:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Set git to not change line endings
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and run PyTest
        run: |
          pip install wheel setuptools
          pip install -r tests/requirements.txt
          pip install . -v
          python -c "import sabyenc3; print(sabyenc3.__version__); print(sabyenc3.decoder_simd);"
          pytest -v --capture=tee-sys